print('enter the first number to add')
first = input()
print('enter the second number to add')
second = input()
print('enter the thrid number to add')
third = input()
print('the sum is:' + first + second + third)
